### ISSUE TITLE
Mark this as the canonical repo

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-bot#1]
<img width="251" alt="screen shot 2018-01-15 at 11 45 49" src="https://user-images.githubusercontent.com/191496/34933886-acac282a-f9e9-11e7-91cb-d79d2d9ce2fa.png">

# TODO

- [x] update references to old repo in `package.json`
- [x] migrate issues (https://github.com/medic/medic-bot/issues/2)
- [x] disable issues, projects etc. from original repo, or delete original repo

**Comment by henokgetachew** [comment]
This has been taken care of.
